CREATE TABLE generation (
    id integer NOT NULL,
    user_id integer NOT NULL,
    generation_id varchar(255) NOT NULL,
    media_id varchar(255) NOT NULL,
    output_media_path varchar(255),
    model_id integer NOT NULL,
    prompt text,
    negative_prompt text,
    settings jsonb NOT NULL,
    attributes jsonb NOT NULL,
    status varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    seed numeric(50,10) NOT NULL,
    controlnet_image_path varchar(255),
    facelock_image_path varchar(255),
    published_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    thumbnail_image_path varchar(255),
    style_id integer,
    segment_image_path varchar(255),
    segment_prompt jsonb,
    true_touch_image_path varchar(255),
    video_attributes jsonb,
    metadata_id integer,
    generation_type varchar(255)
);
