// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package generations

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Generation struct {
	ID                  int32          `db:"id"`
	UserID              int32          `db:"user_id"`
	GenerationID        string         `db:"generation_id"`
	MediaID             string         `db:"media_id"`
	OutputMediaPath     *string        `db:"output_media_path"`
	ModelID             int32          `db:"model_id"`
	Prompt              pgtype.Text    `db:"prompt"`
	NegativePrompt      pgtype.Text    `db:"negative_prompt"`
	Settings            []byte         `db:"settings"`
	Attributes          []byte         `db:"attributes"`
	Status              string         `db:"status"`
	Type                string         `db:"type"`
	Seed                pgtype.Numeric `db:"seed"`
	ControlnetImagePath *string        `db:"controlnet_image_path"`
	FacelockImagePath   *string        `db:"facelock_image_path"`
	PublishedAt         *time.Time     `db:"published_at"`
	UpdatedAt           time.Time      `db:"updated_at"`
	CreatedAt           time.Time      `db:"created_at"`
	ThumbnailImagePath  *string        `db:"thumbnail_image_path"`
	StyleID             pgtype.Int4    `db:"style_id"`
	SegmentImagePath    *string        `db:"segment_image_path"`
	SegmentPrompt       []byte         `db:"segment_prompt"`
	TrueTouchImagePath  *string        `db:"true_touch_image_path"`
	VideoAttributes     []byte         `db:"video_attributes"`
	MetadataID          pgtype.Int4    `db:"metadata_id"`
	GenerationType      *string        `db:"generation_type"`
}
