// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package generations

import (
	"context"
	"time"
)

const countSuccessfullImageGeneration = `-- name: CountSuccessfullImageGeneration :one
SELECT 
	COUNT(1) as total
FROM generation 
WHERE type=$1
	AND status='success' 
	AND video_attributes IS NULL 
	AND created_at < $2 AND created_at >= $3
`

type CountSuccessfullImageGenerationParams struct {
	Type        string    `db:"type"`
	CreatedAt   time.Time `db:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2"`
}

func (q *Queries) CountSuccessfullImageGeneration(ctx context.Context, arg CountSuccessfullImageGenerationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfullImageGeneration, arg.Type, arg.CreatedAt, arg.CreatedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSuccessfullImageGenerationByUser = `-- name: CountSuccessfullImageGenerationByUser :one
SELECT 
	COUNT(1) as total
FROM generation 
WHERE type=$1
	AND user_id = $2
	AND status='success' 
	AND video_attributes IS NULL 
	AND created_at < $3 AND created_at >= $4
`

type CountSuccessfullImageGenerationByUserParams struct {
	Type        string    `db:"type"`
	UserID      int32     `db:"user_id"`
	CreatedAt   time.Time `db:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2"`
}

func (q *Queries) CountSuccessfullImageGenerationByUser(ctx context.Context, arg CountSuccessfullImageGenerationByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfullImageGenerationByUser,
		arg.Type,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const listSuccessfullImageGeneration = `-- name: ListSuccessfullImageGeneration :many
SELECT 
	generation_id
	,media_id
	,output_media_path 
	,created_at
FROM generation 
WHERE type=$1
	AND status='success' 
	AND video_attributes IS NULL 
	AND created_at < $2 AND created_at >= $3
ORDER BY created_at DESC
LIMIT $4
`

type ListSuccessfullImageGenerationParams struct {
	Type        string    `db:"type"`
	CreatedAt   time.Time `db:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2"`
	Limit       int32     `db:"limit"`
}

type ListSuccessfullImageGenerationRow struct {
	GenerationID    string    `db:"generation_id"`
	MediaID         string    `db:"media_id"`
	OutputMediaPath *string   `db:"output_media_path"`
	CreatedAt       time.Time `db:"created_at"`
}

func (q *Queries) ListSuccessfullImageGeneration(ctx context.Context, arg ListSuccessfullImageGenerationParams) ([]ListSuccessfullImageGenerationRow, error) {
	rows, err := q.db.Query(ctx, listSuccessfullImageGeneration,
		arg.Type,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuccessfullImageGenerationRow
	for rows.Next() {
		var i ListSuccessfullImageGenerationRow
		if err := rows.Scan(
			&i.GenerationID,
			&i.MediaID,
			&i.OutputMediaPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuccessfullImageGenerationByUser = `-- name: ListSuccessfullImageGenerationByUser :many
SELECT 
	generation_id
	,media_id
	,output_media_path 
	,created_at
FROM generation 
WHERE type=$1
	AND user_id = $2
	AND status='success' 
	AND video_attributes IS NULL 
	AND created_at < $3 AND created_at >= $4
ORDER BY created_at DESC
LIMIT $5
`

type ListSuccessfullImageGenerationByUserParams struct {
	Type        string    `db:"type"`
	UserID      int32     `db:"user_id"`
	CreatedAt   time.Time `db:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2"`
	Limit       int32     `db:"limit"`
}

type ListSuccessfullImageGenerationByUserRow struct {
	GenerationID    string    `db:"generation_id"`
	MediaID         string    `db:"media_id"`
	OutputMediaPath *string   `db:"output_media_path"`
	CreatedAt       time.Time `db:"created_at"`
}

func (q *Queries) ListSuccessfullImageGenerationByUser(ctx context.Context, arg ListSuccessfullImageGenerationByUserParams) ([]ListSuccessfullImageGenerationByUserRow, error) {
	rows, err := q.db.Query(ctx, listSuccessfullImageGenerationByUser,
		arg.Type,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuccessfullImageGenerationByUserRow
	for rows.Next() {
		var i ListSuccessfullImageGenerationByUserRow
		if err := rows.Scan(
			&i.GenerationID,
			&i.MediaID,
			&i.OutputMediaPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
