[supervisord]
nodaemon=true
user=root

[program:go-server]
command=/app/optimux/server
autostart=true
autorestart=false
startretries=3
user=root
stdout_logfile=/var/log/app.log
stderr_logfile=/var/log/app.err
environment=
    S3_BASE_URL="%(ENV_S3_BASE_URL)s",
    CGO_CFLAGS_ALLOW="%(ENV_CGO_CFLAGS_ALLOW)s",
    ORIGINS="%(ENV_ORIGINS)s",
    QSIZE="%(ENV_QSIZE)s",
    ENV="%(ENV_ENVIRONMENT)s",
    DOMAIN="%(ENV_DOMAIN)s",
    PG_URL="%(ENV_PG_URL)s"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=false
startretries=3
user=root
stdout_logfile=/var/log/nginx_supervisor.log
stderr_logfile=/var/log/nginx_supervisor.err
