// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package mediametadata

import (
	"time"
)

type ProcessedMediaMetadata struct {
	MediaID     string     `db:"media_id"`
	Source      string     `db:"source"`
	Version     string     `db:"version"`
	Metadata    []byte     `db:"metadata"`
	CreatedAt   time.Time  `db:"created_at"`
	Status      string     `db:"status"`
	ProcessedAt *time.Time `db:"processed_at"`
}
