// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package mediametadata

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const selectMediaByMediaIDs = `-- name: SelectMediaByMediaIDs :many
SELECT
	media_id
	,source
	,version
	,metadata
	,created_at
	,processed_at
FROM processed_media_metadatas
WHERE (media_id, version) = ANY($1::media_version_pair[]) AND status = $2
`

type SelectMediaByMediaIDsParams struct {
	Column1 []string `db:"column_1"`
	Status  string   `db:"status"`
}

type SelectMediaByMediaIDsRow struct {
	MediaID     string     `db:"media_id"`
	Source      string     `db:"source"`
	Version     string     `db:"version"`
	Metadata    []byte     `db:"metadata"`
	CreatedAt   time.Time  `db:"created_at"`
	ProcessedAt *time.Time `db:"processed_at"`
}

func (q *Queries) SelectMediaByMediaIDs(ctx context.Context, arg SelectMediaByMediaIDsParams) ([]SelectMediaByMediaIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectMediaByMediaIDs, pq.Array(arg.Column1), arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectMediaByMediaIDsRow
	for rows.Next() {
		var i SelectMediaByMediaIDsRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Source,
			&i.Version,
			&i.Metadata,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
